name: 02 - Eventos
on:
  schedule:
    - cron: "* * * * *"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:          
      - name: ShowTrigger
        run: |
          echo "Event name: ${{ github.event_name }}" 